eureka:
  server:
    account: admin
    password: root
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://${eureka.server.account}:${eureka.server.password}@localhost:8021/eureka

spring:
  application:
    name: ZUUL

server:
  port: 8023

#zuul监控界面(开发时配置为*，上线不要配置)
management:
  endpoints:
    web:
      exposure:
        include: '*'

