
eureka:
  server:
    account: admin
    password: root
  instance:
    hostname: localhost
  client:
    # 注册到eureka
    registerWithEureka: true
    # 从eureka获取注册信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.server.account}:${eureka.server.password}@${eureka.instance.hostname}:8022/eureka/

server:
  port: 8021

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: root